apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity: 
    storage: 10Mi
  volumeMode: Filesystem
  # claimRef:
  #   name: demo-pvc
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"